ZOLA_ROOT="${ZOLA_ROOT:-".."}"
GIT_DIR="ZOLA_ROOT/../"
STATIC_DIR="$ZOLA_ROOT/static"
CONFIG_TOML="$ZOLA_ROOT/-config.toml"

function escape() {
  # shellcheck disable=SC2001
  echo "$1" | sed 's|/|\\/|g'
}

START_GUARD="$(escape '# Autogenerated by ./z-dev-scripts/static-watcher.sh')"
END_GUARD="$(escape '# End of Autogenerated by ./z-dev-scripts/static-watcher.sh')"

function sed_template() {
  echo "/$START_GUARD/,/$END_GUARD/{$1
  }"
}

function make_sed_remove() {
  sed_template "/$1/d"
}

function make_sed_insert() {
  sed_template "/$1/d; /$END_GUARD/i $1 = $2"
}

function guarded_sed() {
  sed -i~ "$@"
}

function format_name() {
  echo "static_versions.\"$(escape "$1")\""
}

function format_value() {
  echo "\"$1\""
}

function format_row() {
  echo "$(format_name "$1") = $(format_value "$2")"
}

function handle_delete() {
  filename="$1"
  relname="$(realpath -s --relative-to="$STATIC_DIR" "$filename")"
  echo "Deleting $relname"
  guarded_sed "$(make_sed_remove "$(format_name "$relname")")" "$CONFIG_TOML"
}

function get_version() {
  filename="$1"
  if [[ $(git status --porcelain "$filename") ]]; then
    echo "r$(hexdump -vn16 -e'4/4 "%08X" 1 "\n"' /dev/urandom)"
  else
    echo "g$(git log --pretty=format:"%H" -1 -- "$filename")"
  fi | head -c 8
}

function handle_write() {
  filename="$1"
  relname="$(realpath -s --relative-to="$STATIC_DIR" "$filename")"
  echo "Updating $relname"
  guarded_sed "$(make_sed_insert "$(format_name "$relname")" "$(format_value "$(get_version "$filename")")")" "$CONFIG_TOML"
}

function handle_event() {
  filename="$1$2"
  event="$3"

  case "$event" in
    "DELETE")
      handle_delete "$filename"
      ;;
    "CLOSE_WRITE,CLOSE")
      handle_write "$filename"
      ;;
  esac
}

function watch() {
  inotifywait -q -m -r -e close_write -e delete "$STATIC_DIR" |
  while read -r dir event filename _leftover; do
    handle_event "$dir" "$filename" "$event";
  done
}

function build() {
  while IFS= read -r filename
  do
    handle_write "$filename"
  done < <(find "$STATIC_DIR" -type f)
}

build
