ZOLA_ROOT="${ZOLA_ROOT:-".."}"
STATIC_DIR="$ZOLA_ROOT/static"
STATIC_VERSIONS_OUTPUT="$ZOLA_ROOT/templates/static_versions.generated.html"
FILE_TEMPLATE_HEAD=$(cat <<'END_FILE_TEMPLATE'
{% macro get_version(filename) %}
    {% set search = filename ~ " = " %}
    {% for entry in [

END_FILE_TEMPLATE
)
FILE_TEMPLATE_TAIL=$(cat <<'END_FILE_TEMPLATE'
    ] %}
        {% if entry is starting_with(search) %}
            {{ entry | replace(from=search, to="") }}
        {% endif %}
    {% endfor %}
{% endmacro get_version %}

END_FILE_TEMPLATE
)

function escape() {
  # shellcheck disable=SC2001
  echo "$1" | sed 's|/|\\/|g'
}

START_GUARD="$(escape '# Autogenerated by ./z-dev-scripts/static-watcher.sh')"
END_GUARD="$(escape '# End of Autogenerated by ./z-dev-scripts/static-watcher.sh')"

function sed_template() {
  echo "/$START_GUARD/,/$END_GUARD/{$1
  }"
}

function make_sed_remove() {
  sed_template "/$1/d"
}

function make_sed_insert() {
  sed_template "/$1/d; /$END_GUARD/i $1 = $2"
}

function guarded_sed() {
  sed -i~ "$@"
}

function format_name() {
  echo "static_versions.\"$(escape "$1")\""
}

function format_value() {
  echo "\"$1\""
}

function format_row() {
  echo "$(format_name "$1") = $(format_value "$2")"
}

function handle_delete() {
  filename="$1"
  relname="$(realpath -s --relative-to="$STATIC_DIR" "$filename")"
  echo "Deleting $relname"
  guarded_sed "$(make_sed_remove "$(format_name "$relname")")" "$CONFIG_TOML"
}

function get_version() {
  filename="$1"
  if [[ $(git status --porcelain "$filename") ]]; then
    echo "r$(hexdump -vn16 -e'4/4 "%08X" 1 "\n"' /dev/urandom)"
  else
    echo "g$(git log --pretty=format:"%H" -1 -- "$filename")"
  fi | head -c 8
}

function handle_write() {
  filename="$1"
  relname="$(realpath -s --relative-to="$STATIC_DIR" "$filename")"
  files["$relname"]="$(get_version "$filename")"
}

function handle_event() {
  filename="$1$2"
  event="$3"

  case "$event" in
    "DELETE")
      handle_delete "$filename"
      ;;
    "CLOSE_WRITE,CLOSE")
      handle_write "$filename"
      ;;
  esac
}

function collect() {
  while IFS= read -r filename
  do
    handle_write "$filename"
  done < <(find "$STATIC_DIR" -type f)
}

function output() {
  {
    echo "$FILE_TEMPLATE_HEAD"
    for i in "${!files[@]}"
    do
      echo "        \"$i = ${files[$i]}\","
    done
    echo "$FILE_TEMPLATE_TAIL"
  } > "$STATIC_VERSIONS_OUTPUT"
}

function watch_static() {
  echo "Started static version watcher"
  declare -A files
  inotifywait -q -m -r -e close_write -e delete "$STATIC_DIR" |
  while read -r dir event filename _leftover; do
    handle_event "$dir" "$filename" "$event";
    output
  done
}

function build() {
  declare -A files
  collect
  output
}