on:
  release:
    types: [published]
  workflow_dispatch:
name: Deploy website on release
jobs:
  web-deploy:
    name: Deploy
    environment: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: FTP upload
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.forest-school.am
        server-dir: public_html/
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
