on:
  push:
    branches:
      master
  workflow_dispatch:
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    environment: nextgen
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4


    - name: SFTP upload
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: vps-usa.forest-school.am
        username: ${{ vars.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 2022
        uploads: |
          ./ => ./